### ISSUE TITLE
Add Heapsort

### ISSUE THREAD

**Issue by yangshun** [yangshun/lago#11]
http://www.geeksforgeeks.org/heap-sort/

**Comment by brandonmanke** [comment]
I would like to work on this, if that is ok?

**Comment by yangshun** [comment]
Sure! Please note that tests have to be added. Please refer to the link in the description for the implementation.

**Comment by brandonmanke** [comment]
Will do! Quick question in regards to testing (correct me if I am wrong), but there wouldn't be any extra test cases for Heapsort, when compared to other sorting algorithm tests you have so far. Correct? Since the `sortingInputs.js` covers mostly everything.

**Comment by yangshun** [comment]
Closed via #26. Thanks @brandonmanke !
