### ISSUE TITLE
Add Binary Search

### ISSUE THREAD

**Issue by yangshun** [yangshun/lago#16]
- [x] Search for target
- [x] Bisect left
- [x] Bisect right

References:
- https://docs.python.org/2/library/bisect.html

**Comment by Ashwin7mak** [comment]
I would like to add Binary Search algorithm. Can I work on this open issue ?

**Comment by Ashwin7mak** [comment]
This issue is no more opened. I guess it should be marked as closed.

**Comment by yangshun** [comment]
Bisect left and bisect right isn't done yet. Feel free to take it up.
