### ISSUE TITLE
Add Graph Node

### ISSUE THREAD

**Issue by mauris** [yangshun/lago#36]
A graph can have a value, and zero, one or more neighbours.

**Comment by mauris** [comment]
@yangshun we also need to consider the 3 way we represent graphs. *cough* Dr Steven Halim *cough*

**Comment by san7988** [comment]
Hi @yangshun, are we still open to contributing to this repo?

**Comment by yangshun** [comment]
Yeah go ahead

**Comment by yangshun** [comment]
We're not going to implement a GraphNode as we have opted for a Graph data structure that encapsulates the representation for Nodes and Edges.
