### ISSUE TITLE
Add Binary Tree

### ISSUE THREAD

**Issue by yangshun** [yangshun/lago#4]
The following classes should support the following operations:

`BinaryTree` class:

- [x] `constructor()`
- [x] `getRoot()`
- [x] `height()`
- [x] `size()`
- [x] `isBalanced()`
- [x] `isComplete()`
- [x] `preOrder()`
- [x] `inOrder()`
- [x] `postOrder()`

`BinarySearchTree` class which extends from `BinaryTree`:

- [x] `insert()`
- [x] `search()`
- [x] `delete()`
- [x] `getMinimum()`
- [x] `getMaximum()`

**Comment by mauris** [comment]
This can be worked on once #32 are resolved with merge PR of #34.

**Comment by mauris** [comment]
@yangshun `isBalanced()` doesn't seem to be a standard API for a binary tree. do we use the AVL definition of balancing for this method?

**Comment by PranjalAgni** [comment]
Can I work on this.

**Comment by yangshun** [comment]
Thanks but it's already almost done.

**Comment by yangshun** [comment]
Many thanks to @utkarsh261 for completing the final task within this issue!
