### ISSUE TITLE
Add UFDS

### ISSUE THREAD

**Issue by mauris** [yangshun/lago#41]
- [x] initialize(n)
- [x] findSet(x)
- [x] isSameSet(x, y)
- [x] unionSet(x, y)

@yangshun how could we have missed this DS out for so long. @stevenhalim XD

**Comment by stevenhalim** [comment]
what is this UFDS thingy btw (sam/yangshun)?

Regards,

Steven Halim (Dr.)
Senior Lecturer
School of Computing, National University of Singapore
<http://www.comp.nus.edu.sg/~stevenha>
https://visualgo.net and https://cpbook.net

**Comment by yangshun** [comment]
Probably Union Find/Disjoint Set

**Comment by stevenhalim** [comment]
yeah of course I know UFDS is https://visualgo.net/en/ufds
but what is the context of "Add UFDS (#41)" Github issue??

Regards,

Steven Halim (Dr.)
Senior Lecturer
School of Computing, National University of Singapore
<http://www.comp.nus.edu.sg/~stevenha>
https://visualgo.net and https://cpbook.net

**Comment by mauris** [comment]
@yangshun has been building an algorithms library (i.e. this lago repository) in JavaScript and we've not added UFDS for implementation for some time. (but we've not forgotten what you've taught!)
