### ISSUE TITLE
Add Heap

### ISSUE THREAD

**Issue by yangshun** [yangshun/lago#6]
- `Heap` class:
  - [ ] `constructor()`
  - [ ] `size`
  - [ ] `isEmpty()`
  - [ ] `peek()` // max or min depending on type of heap
  - [ ] `insert()`
  - [ ] `extract()`
  - [ ] `static heapify<T>(arr: T[])`
- [ ] should cover min heap
- [ ] should cover max heap

References
- https://docs.python.org/3.7/library/heapq.html
- https://medium.com/basecs/heapify-all-the-things-with-heap-sort-55ee1c93af82

**Comment by amtb** [comment]
hi @yangshun can I work on this ?

**Comment by yangshun** [comment]
Sure

**Comment by yangshun** [comment]
Note that some part of https://github.com/yangshun/lago/pull/66/ will cover this. Might make sense to add stuff on top of the existing Priority Queue data structure.

**Comment by amtb** [comment]
dully noted, I will check.
Thanks
