### ISSUE TITLE
[Question] Double-ended Queue JS implementation time complexity

### ISSUE THREAD

**Issue by coltonehrman** [yangshun/lago#60]
I see you are using `Array.prototype.unshift` and `Array.prototype.shift` as methods in the double-ended queue DS.
https://github.com/yangshun/lago/blob/2ebdb22360d4ba1ed7f3c5cfe7729283bdb40608/lib/data-structures/Deque.js#L17
https://github.com/yangshun/lago/blob/2ebdb22360d4ba1ed7f3c5cfe7729283bdb40608/lib/data-structures/Deque.js#L25

I believe these methods have `O(n)` time complexity, shouldn't the queue's operations all be `O(1)` time complexity?

**Comment by coltonehrman** [comment]
Ah... sorry, I should have dug deeper into the code before making these assumptions, I now realized you have a custom DoublyLinkedList class that has the same-named methods as the built-in array.

**Comment by yangshun** [comment]
That's awesome, thanks for digging deeper! :)
