### ISSUE TITLE
Inversion of Control

### ISSUE THREAD

**Issue by mauris** [yangshun/lago#82]
Currently most of the data structures accept `number` values and uses `>` or `<` (or variant) for comparison. As this is intended to be a library, we should incorporate IoC as much as possible.

A few ways we can do this include:

- [ ] adding generic parameters to determine what are the values that the data structure should accept
- [ ] accepting comparators to compare the values

I will assess and determine which data structures / algos can be done.

**Comment by yangshun** [comment]
> As this is intended to be a library

Probably not worth it haha. Don't think I'll spend more time on this. This repo is more useful as reference for educational purpose. Making it production-ready will make the code harder to read and go against that purpose.

**Comment by mauris** [comment]
I think this was discussed before long time ago and you gave the same answer 😆 aligned (again)

In most cases, I think devs will do a copy-paste-modify to get a specific algo / data structure into their codebase for their specific use case.
